server:
  rootPath: '/api/'

dbConfig:
  host: ds127968.mlab.com
  port: 27968
  dbName: heroku_n91f12d8
  user: heroku_n91f12d8
  password: ${MONGODB_PASS}

server:
  applicationConnectors:
    - type: http
      port: ${PORT:-8080}
  adminConnectors:
    - type: http
      port: 8081


logging:
  level: INFO
  loggers:
    name.aknights: DEBUG
