server:
  rootPath: '/api/'

env: prod

jwtTokenSecret: "cV2uHolULHblnTjc28BGbahb2UjwqN_iEu5yfgMo22KrOVr_9zeQ2i2zzN6ZwgXL"
expectedAudience: "T2HQUxSUXXutd1rigWpUvdEONkd5s1gm"

dbConfig:
  host: ds127968.mlab.com
  port: 27968
  dbName: heroku_n91f12d8
  user: heroku_n91f12d8
  password: ${MONGODB_PASS}

yahooConfig:
  apiUrl: http://query.yahooapis.com/v1/public/yql

server:
  applicationConnectors:
    - type: http
      port: ${PORT:-8080}
  adminConnectors:
    - type: http
      port: 8081


logging:
  level: INFO
  loggers:
    name.aknights: DEBUG
