logging:
  level: INFO
  loggers:
    name.aknights: DEBUG

server:
  rootPath: '/api/'


mongoDbUri: 'mongodb://heroku_n91f12d8:ct9drvuqreb10oc6gc3risge5q@ds127968.mlab.com:27968/heroku_n91f12d8'
mongoDbName: 'heroku_n91f12d8'